import os
import json
import pandas as pd
from openai import OpenAI

# -----------------------------------
# Load API Key (Hugging Face env variable)
# -----------------------------------
API_KEY = os.getenv("NVIDIA_API_KEY")

if not API_KEY:
    print("WARNING: NVIDIA_API_KEY not found. LLM disabled.")
    client = None
else:
    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=API_KEY
    )

# -----------------------------------
# Load Metadata CSV
# -----------------------------------
metadata_path = "data/venomstatus_with_antivenom.csv"
df = pd.read_csv(metadata_path)

# -----------------------------------
# Function: Get Snake Description
# -----------------------------------
def get_snake_description(species_name: str) -> str:

    if client is None:
        return "LLM service unavailable"

    system_prompt = (
        "You are a professional snake species expert and herpetologist. "
        "Provide accurate, scientific, and concise descriptions of snake species."
    )

    user_prompt = (
        f"Describe the snake species '{species_name}' including:\n"
        f"- Venom type and danger level\n"
        f"- Habitat and geographic distribution\n"
        f"- Behavior and typical environment\n"
        f"- Conservation or ecological importance\n\n"
        f"Provide a single short paragraph (max 20 words)."
    )

    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,
            stream=False
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        return f"Error generating description: {str(e)}"


# -----------------------------------
# Allowed Species List
# -----------------------------------
ALLOWED_SPECIES = [
    "Acanthophis antarcticus",
    "Acanthophis hawkei",
    "Acanthophis praelongus",
    "Acanthophis pyrrhus",
    "Acanthophis rugosus",
    "Acanthophis wellsi",
    "Achalinus formosanus",
    "Achalinus niger",
    "Achalinus rufescens",
    "Acrantophis dumerili",
    "Acrantophis madagascariensis",
    "Acrochordus arafurae",
    "Acrochordus granulatus",
    "Adelphicos quadrivirgatum",
    "Afrotyphlops bibronii",
    "Afrotyphlops schlegelii",
    "Agkistrodon bilineatus",
    "Agkistrodon conanti",
    "Agkistrodon contortrix",
    "Agkistrodon laticinctus",
    "Agkistrodon piscivorus",
    "Agkistrodon russeolus",
    "Agkistrodon taylori",
    "Ahaetulla fasciolata",
    "Ahaetulla mycterizans",
    "Ahaetulla nasuta",
    "Ahaetulla prasina",
    "Aipysurus laevis",
    "Alsophis rufiventris",
    "Amblyodipsas polylepis",
    "Amphiesma stolatum",
    "Anilius scytale",
    "Antaresia childreni",
    "Antaresia maculosa",
    "Antaresia perthensis",
    "Antaresia stimsoni",
    "Aparallactus capensis",
    "Aplopeltura boa",
    "Argyrogena fasciolata",
    "Arizona elegans",
    "Aspidelaps lubricus",
    "Aspidites melanocephalus",
    "Aspidites ramsayi",
    "Asthenodipsas vertebralis",
    "Atheris ceratophora",
    "Atheris chlorechis",
    "Atheris squamigera",
    "Atractaspis bibronii",
    "Atractus crassicaudatus",
    "Atropoides mexicanus",
    "Atropoides nummifer",
    "Austrelaps ramsayi",
    "Austrelaps superbus",
    "Azemiops feae",
    "Bitis arietans",
    "Bitis atropos",
    "Bitis caudalis",
    "Bitis gabonica",
    "Bitis nasicornis",
    "Bitis peringueyi",
    "Boa constrictor",
    "Boa imperator",
    "Boaedon capensis",
    "Boaedon fuliginosus",
    "Bogertophis rosaliae",
    "Bogertophis subocularis",
    "Boiga ceylonensis",
    "Boiga cyanea",
    "Boiga cynodon",
    "Boiga dendrophila",
    "Boiga drapiezii",
    "Boiga irregularis",
    "Boiga jaspidea",
    "Boiga kraepelini",
    "Boiga multomaculata",
    "Boiga nigriceps",
    "Boiga trigonata",
    "Bolyeria multocarinata",
    "Borikenophis portoricensis",
    "Bothriechis aurifer",
    "Bothriechis lateralis",
    "Bothriechis marchi",
    "Bothriechis nigroviridis",
    "Bothriechis schlegelii",
    "Bothrocophias campbelli",
    "Bothrocophias microphthalmus",
    "Bothrops alternatus",
    "Bothrops asper",
    "Bothrops atrox",
    "Bothrops bilineatus",
    "Bothrops diporus",
    "Bothrops jararaca",
    "Bothrops jararacussu",
    "Bothrops moojeni",
    "Brachyurophis australis",
    "Bungarus caeruleus",
    "Bungarus candidus",
    "Bungarus fasciatus",
    "Bungarus flaviceps",
    "Bungarus multicinctus",
    "Cacophis churchilli",
    "Cacophis krefftii",
    "Cacophis squamulosus",
    "Calamaria pavimentata",
    "Calamaria schlegeli",
    "Calamaria schmidti",
    "Calliophis bivirgatus",
    "Calliophis intestinalis",
    "Calloselasma rhodostoma",
    "Caraiba andreae",
    "Carphophis amoenus",
    "Carphophis vermis",
    "Causus defilippii",
    "Causus rhombeatus",
    "Cemophora coccinea",
    "Cerastes cerastes",
    "Cerastes gasperettii",
    "Cerastes vipera",
    "Cerberus rynchops",
    "Cerberus schneiderii",
    "Cerrophidion godmani",
    "Cerrophidion wilsoni",
    "Charina bottae",
    "Charina umbratica",
    "Chilabothrus angulifer",
    "Chilabothrus inornatus",
    "Chilabothrus subflavus",
    "Chilomeniscus stramineus",
    "Chironius bicarinatus",
    "Chironius carinatus",
    "Chironius exoletus",
    "Chironius fuscus",
    "Chironius grandisquamis",
    "Chironius monticola",
    "Chironius scurrulus",
    "Chrysopelea ornata",
    "Chrysopelea paradisi",
    "Chrysopelea pelias",
    "Clelia clelia",
    "Clelia equatoriana",
    "Clonophis kirtlandii",
    "Coelognathus flavolineatus",
    "Coelognathus helena",
    "Coelognathus radiatus",
    "Coluber constrictor",
    "Coniophanes fissidens",
    "Coniophanes imperialis",
    "Coniophanes meridanus",
    "Coniophanes piceivittis",
    "Coniophanes schmidti",
    "Conophis lineatus",
    "Conopsis biserialis",
    "Conopsis lineata",
    "Conopsis nasus",
    "Contia longicaudae",
    "Contia tenuis",
    "Corallus annulatus",
    "Corallus batesii",
    "Corallus caninus",
    "Corallus hortulanus",
    "Corallus ruschenbergerii",
    "Coronella austriaca",
    "Coronella girondica",
    "Crotalus adamanteus",
    "Crotalus aquilus",
    "Crotalus atrox",
    "Crotalus basiliscus",
    "Crotalus catalinensis",
    "Crotalus cerastes",
    "Crotalus cerberus",
    "Crotalus culminatus",
    "Crotalus durissus",
    "Crotalus enyo",
    "Crotalus horridus",
    "Crotalus intermedius",
    "Crotalus lepidus",
    "Crotalus mitchellii",
    "Crotalus molossus",
    "Crotalus morulus",
    "Crotalus oreganus",
    "Crotalus ornatus",
    "Crotalus polystictus",
    "Crotalus pricei",
    "Crotalus pyrrhus",
    "Crotalus ravus",
    "Crotalus ruber",
    "Crotalus scutulatus",
    "Crotalus simus",
    "Crotalus stephensi",
    "Crotalus tigris",
    "Crotalus totonacus",
    "Crotalus triseriatus",
    "Crotalus tzabcan",
    "Crotalus viridis",
    "Crotalus willardi",
    "Crotaphopeltis hotamboeia",
    "Cryptophis nigrescens",
    "Cubophis cantherigerus",
    "Cubophis caymanus",
    "Cubophis vudii",
    "Cylindrophis ruffus",
    "Daboia mauritanica",
    "Daboia palaestinae",
    "Daboia russelii",
    "Dasypeltis scabra",
    "Deinagkistrodon acutus",
    "Demansia papuensis",
    "Demansia psammophis",
    "Demansia torquata",
    "Demansia vestigiata",
    "Dendrelaphis caudolineatus",
    "Dendrelaphis cyanochloris",
    "Dendrelaphis formosus",
    "Dendrelaphis haasi",
    "Dendrelaphis kopsteini",
    "Dendrelaphis pictus",
    "Dendrelaphis punctulatus",
    "Dendrelaphis tristis",
    "Dendroaspis angusticeps",
    "Dendroaspis jamesoni",
    "Dendroaspis polylepis",
    "Dendroaspis viridis",
    "Dendrophidion bivittatus",
    "Dendrophidion dendrophis",
    "Dendrophidion percarinatum",
    "Denisonia devisi",
    "Diadophis punctatus",
    "Dipsadoboa aulica",
    "Dipsas brevifacies",
    "Dipsas catesbyi",
    "Dipsas gracilis",
    "Dipsas indica",
    "Dispholidus typus",
    "Dolichophis caspius",
    "Dolichophis jugularis",
    "Drepanoides anomalus",
    "Dromicodryas bernieri",
    "Drymarchon corais",
    "Drymarchon couperi",
    "Drymarchon melanurus",
    "Drymobius margaritiferus",
    "Drymoluber dichrous",
    "Dryophiops rubescens",
    "Drysdalia coronoides",
    "Drysdalia rhodogaster",
    "Duberria lutrix",
    "Echinanthera melanostigma",
    "Echiopsis curta",
    "Echis carinatus",
    "Echis coloratus",
    "Echis omanensis",
    "Echis pyramidum",
    "Eirenis modestus",
    "Elaphe carinata",
    "Elaphe climacophora",
    "Elaphe dione",
    "Elaphe quadrivirgata",
    "Elaphe quatuorlineata",
    "Elaphe sauromates",
    "Elaphe schrenckii",
    "Elaphe taeniura",
    "Enhydris enhydris",
    "Enulius flavitorques",
    "Epicrates cenchria",
    "Epicrates maurus",
    "Epictia goudotii",
    "Erpeton tentaculatum",
    "Erythrolamprus aesculapii",
    "Erythrolamprus bizona",
    "Erythrolamprus epinephalus",
    "Erythrolamprus melanotus",
    "Erythrolamprus miliaris",
    "Erythrolamprus poecilogyrus",
    "Erythrolamprus reginae",
    "Erythrolamprus typhlus",
    "Eryx colubrinus",
    "Eryx conicus",
    "Eryx jaculus",
    "Eryx jayakari",
    "Eryx johnii",
    "Eunectes murinus",
    "Eunectes notaeus",
    "Euprepiophis conspicillata",
    "Euprepiophis mandarinus",
    "Farancia abacura",
    "Farancia erytrogramma",
    "Ficimia publia",
    "Ficimia streckeri",
    "Fordonia leucobalia",
    "Fowlea flavipunctatus",
    "Fowlea piscator",
    "Furina diadema",
    "Furina ornata",
    "Geophis hoffmanni",
    "Geophis semidoliatus",
    "Gerarda prevostiana",
    "Gloydius blomhoffii",
    "Gloydius brevicaudus",
    "Gloydius halys",
    "Gloydius intermedius",
    "Gloydius ussuriensis",
    "Gonyosoma boulengeri",
    "Gonyosoma oxycephalum",
    "Gyalopion canum",
    "Gyalopion quadrangulare",
    "Haldea striatula",
    "Hapsidophrys smaragdinus",
    "Hebius beddomei",
    "Hebius sauteri",
    "Hebius vibakari",
    "Helicops angulatus",
    "Helicops infrataeniatus",
    "Helicops leopardinus",
    "Hemachatus haemachatus",
    "Hemiaspis signata",
    "Hemorrhois hippocrepis",
    "Hemorrhois nummifer",
    "Hemorrhois ravergieri",
    "Heterodon kennerlyi",
    "Heterodon nasicus",
    "Heterodon platirhinos",
    "Heterodon simus",
    "Hierophis gemonensis",
    "Hierophis viridiflavus",
    "Homalopsis buccata",
    "Homoroselaps lacteus",
    "Hoplocephalus bitorquatus",
    "Hoplocephalus bungaroides",
    "Hoplocephalus stephensii",
    "Hydrodynastes gigas",
    "Hydrophis platurus",
    "Hypnale hypnale",
    "Hypsiglena chlorophaea",
    "Hypsiglena jani",
    "Hypsiglena ochrorhynchus",
    "Hypsiglena torquata",
    "Hypsirhynchus parvifrons",
    "Hypsiscopus plumbea",
    "Imantodes cenchoa",
    "Imantodes gemmistratus",
    "Imantodes inornatus",
    "Imantodes tenuissimus",
    "Indotyphlops braminus",
    "Lachesis muta",
    "Lampropeltis abnorma",
    "Lampropeltis alterna",
    "Lampropeltis annulata",
    "Lampropeltis californiae",
    "Lampropeltis calligaster",
    "Lampropeltis elapsoides",
    "Lampropeltis extenuata",
    "Lampropeltis gentilis",
    "Lampropeltis getula",
    "Lampropeltis holbrooki",
    "Lampropeltis knoblochi",
    "Lampropeltis mexicana",
    "Lampropeltis micropholis",
    "Lampropeltis multifasciata",
    "Lampropeltis nigra",
    "Lampropeltis polyzona",
    "Lampropeltis pyromelana",
    "Lampropeltis ruthveni",
    "Lampropeltis splendida",
    "Lampropeltis triangulum",
    "Lampropeltis zonata",
    "Lamprophis aurora",
    "Lamprophis guttatus",
    "Langaha madagascariensis",
    "Laticauda colubrina",
    "Laticauda laticaudata",
    "Laticauda saintgironsi",
    "Leioheterodon madagascariensis",
    "Leioheterodon modestus",
    "Leptodeira annulata",
    "Leptodeira frenata",
    "Leptodeira maculata",
    "Leptodeira nigrofasciata",
    "Leptodeira polysticta",
    "Leptodeira rhombifera",
    "Leptodeira septentrionalis",
    "Leptodeira splendida",
    "Leptophis ahaetulla",
    "Leptophis depressirostris",
    "Leptophis diplotropis",
    "Leptophis mexicanus",
    "Liasis fuscus",
    "Liasis mackloti",
    "Liasis olivaceus",
    "Lichanura orcutti",
    "Lichanura trivirgata",
    "Liodytes alleni",
    "Liodytes pygaea",
    "Liodytes rigida",
    "Loxocemus bicolor",
    "Lycodon anamallensis",
    "Lycodon aulicus",
    "Lycodon capucinus",
    "Lycodon flavozonatus",
    "Lycodon futsingensis",
    "Lycodon laoensis",
    "Lycodon rufozonatus",
    "Lycodon ruhstrati",
    "Lycodon semicarinatus",
    "Lycodon striatus",
    "Lycodon subannulatus",
    "Lycodon subcinctus",
    "Lycodon travancoricus",
    "Lycodonomorphus inornatus",
    "Lycodonomorphus rufulus",
    "Lycophidion capense",
    "Lygophis anomalus",
    "Lygophis lineatus",
    "Lytorhynchus diadema",
    "Macropisthodon plumbicolor",
    "Macropisthodon rudis",
    "Macroprotodon brevis",
    "Macroprotodon cucullatus",
    "Macrovipera lebetina",
    "Madagascarophis colubrinus",
    "Malayopython reticulatus",
    "Malpolon insignitus",
    "Malpolon moilensis",
    "Malpolon monspessulanus",
    "Manolepis putnami",
    "Masticophis bilineatus",
    "Masticophis flagellum",
    "Masticophis fuliginosus",
    "Masticophis lateralis",
    "Masticophis mentovarius",
    "Masticophis schotti",
    "Masticophis taeniatus",
    "Mastigodryas boddaerti",
    "Mastigodryas danieli",
    "Mastigodryas melanolomus",
    "Mastigodryas pleii",
    "Micruroides euryxanthus",
    "Micrurus alleni",
    "Micrurus browni",
    "Micrurus diastema",
    "Micrurus distans",
    "Micrurus dumerilii",
    "Micrurus fulvius",
    "Micrurus lemniscatus",
    "Micrurus mipartitus",
    "Micrurus mosquitensis",
    "Micrurus nigrocinctus",
    "Micrurus pyrrhocryptus",
    "Micrurus surinamensis",
    "Micrurus tener",
    "Mimophis mahfalensis",
    "Montivipera xanthina",
    "Morelia bredli",
    "Morelia carinata",
    "Morelia spilota",
    "Morelia viridis",
    "Myrrophis chinensis",
    "Naja annulifera",
    "Naja atra",
    "Naja haje",
    "Naja kaouthia",
    "Naja melanoleuca",
    "Naja mossambica",
    "Naja naja",
    "Naja nigricollis",
    "Naja nivea",
    "Naja sputatrix",
    "Naja subfulva",
    "Naja sumatrana",
    "Natrix astreptophora",
    "Natrix helvetica",
    "Natrix maura",
    "Natrix natrix",
    "Natrix tessellata",
    "Nerodia clarkii",
    "Nerodia cyclopion",
    "Nerodia erythrogaster",
    "Nerodia fasciata",
    "Nerodia floridana",
    "Nerodia harteri",
    "Nerodia rhombifer",
    "Nerodia sipedon",
    "Nerodia taxispilota",
    "Ninia atrata",
    "Ninia diademata",
    "Ninia maculata",
    "Ninia sebae",
    "Notechis scutatus",
    "Nothopsis rugosus",
    "Oligodon arnensis",
    "Oligodon fasciolatus",
    "Oligodon formosanus",
    "Oligodon octolineatus",
    "Oligodon taeniolatus",
    "Oligodon trilineatus",
    "Oocatochus rufodorsatus",
    "Opheodrys aestivus",
    "Opheodrys vernalis",
    "Ophiophagus hannah",
    "Ophryacus undulatus",
    "Opisthotropis andersonii",
    "Opisthotropis cheni",
    "Opisthotropis kuatunensis",
    "Oreocryptophis porphyraceus",
    "Orientocoluber spinalis",
    "Ovophis monticola",
    "Ovophis okinavensis",
    "Ovophis tonkinensis",
    "Oxybelis aeneus",
    "Oxybelis brevirostris",
    "Oxybelis fulgidus",
    "Oxyrhopus formosus",
    "Oxyrhopus guibei",
    "Oxyrhopus melanogenys",
    "Oxyrhopus petolarius",
    "Oxyuranus microlepidotus",
    "Oxyuranus scutellatus",
    "Pantherophis alleghaniensis",
    "Pantherophis bairdi",
    "Pantherophis emoryi",
    "Pantherophis guttatus",
    "Pantherophis obsoletus",
    "Pantherophis ramspotti",
    "Pantherophis slowinskii",
    "Pantherophis spiloides",
    "Pantherophis vulpinus",
    "Parasuta dwyeri",
    "Parasuta flagellum",
    "Pareas atayal",
    "Pareas carinatus",
    "Pareas chinensis",
    "Pareas formosensis",
    "Pareas komaii",
    "Pareas margaritophorus",
    "Philodryas argentea",
    "Philodryas baroni",
    "Philodryas chamissonis",
    "Philodryas olfersii",
    "Philodryas patagoniensis",
    "Philothamnus hoplogaster",
    "Philothamnus natalensis",
    "Philothamnus occidentalis",
    "Philothamnus semivariegatus",
    "Phrynonax poecilonotus",
    "Phyllorhynchus browni",
    "Phyllorhynchus decurtatus",
    "Pituophis catenifer",
    "Pituophis deppei",
    "Pituophis lineaticollis",
    "Pituophis melanoleucus",
    "Pituophis vertebralis",
    "Platyceps najadum",
    "Platyceps rhodorachis",
    "Pliocercus elapoides",
    "Pliocercus euryzonus",
    "Porthidium lansbergii",
    "Porthidium nasutum",
    "Porthidium ophryomegas",
    "Porthidium yucatanicum",
    "Protobothrops cornutus",
    "Protobothrops jerdonii",
    "Protobothrops mucrosquamatus",
    "Psammodynastes pictus",
    "Psammodynastes pulverulentus",
    "Psammophis angolensis",
    "Psammophis brevirostris",
    "Psammophis crucifer",
    "Psammophis mossambicus",
    "Psammophis notostictus",
    "Psammophis orientalis",
    "Psammophis schokari",
    "Psammophis subtaeniatus",
    "Psammophis trinasalis",
    "Psammophylax rhombeatus",
    "Pseudablabes patagoniensis",
    "Pseudalsophis biserialis",
    "Pseudaspis cana",
    "Pseudechis australis",
    "Pseudechis guttatus",
    "Pseudechis porphyriacus",
    "Pseudelaphe flavirufa",
    "Pseudelaphe phaescens",
    "Pseudoboa coronata",
    "Pseudoboa neuwiedii",
    "Pseudocerastes persicus",
    "Pseudoleptodeira latifasciata",
    "Pseudonaja affinis",
    "Pseudonaja aspidorhyncha",
    "Pseudonaja mengdeni",
    "Pseudonaja modesta",
    "Pseudonaja nuchalis",
    "Pseudonaja textilis",
    "Pseudorabdion longiceps",
    "Pseudoxenodon macrops",
    "Pseudoxenodon stejnegeri",
    "Ptyas dhumnades",
    "Ptyas fusca",
    "Ptyas korros",
    "Ptyas major",
    "Ptyas mucosa",
    "Python bivittatus",
    "Python breitensteini",
    "Python brongersmai",
    "Python curtus",
    "Python molurus",
    "Python natalensis",
    "Python regius",
    "Python sebae",
    "Ramphotyphlops bipartitus",
    "Regina grahamii",
    "Regina septemvittata",
    "Rena dissecta",
    "Rena dulcis",
    "Rena humilis",
    "Rhabdophis chrysargos",
    "Rhabdophis nigrocinctus",
    "Rhabdophis nuchalis",
    "Rhabdophis subminiatus",
    "Rhabdophis tigrinus",
    "Rhadinaea decorata",
    "Rhadinaea flavilata",
    "Rhadinaea gaigeae",
    "Rhadinaea hesperia",
    "Rhadinaea taeniata",
    "Rhinocheilus lecontei",
    "Rhinotyphlops lalandei",
    "Rhynchocalamus melanocephalus",
    "Salvadora bairdi",
    "Salvadora deserticola",
    "Salvadora grahamiae",
    "Salvadora hexalepis",
    "Salvadora mexicana",
    "Sanzinia madagascariensis",
    "Scaphiodontophis annulatus",
    "Scolecophis atrocinctus",
    "Senticolis triaspis",
    "Sibon annulatus",
    "Sibon longifrenis",
    "Sibon nebulatus",
    "Sibon sanniolus",
    "Sibynophis chinensis",
    "Simalia amethistina",
    "Simalia kinghorni",
    "Simoselaps bertholdi",
    "Sinomicrurus hatori",
    "Sinomicrurus macclellandi",
    "Sinomicrurus sauteri",
    "Sinonatrix aequifasciata",
    "Sinonatrix annularis",
    "Sinonatrix percarinata",
    "Siphlophis cervinus",
    "Siphlophis compressus",
    "Sistrurus catenatus",
    "Sistrurus miliarius",
    "Sistrurus tergeminus",
    "Sonora semiannulata",
    "Spalerosophis diadema",
    "Spilotes pullatus",
    "Spilotes sulphureus",
    "Stegonotus cucullatus",
    "Stenorrhina degenhardtii",
    "Stenorrhina freminvillei",
    "Storeria dekayi",
    "Storeria hidalgoensis",
    "Storeria occipitomaculata",
    "Storeria storerioides",
    "Storeria victa",
    "Suta punctata",
    "Suta suta",
    "Symphimus mayae",
    "Tachymenis chilensis",
    "Tachymenis peruviana",
    "Tantilla bocourti",
    "Tantilla coronata",
    "Tantilla cucullata",
    "Tantilla gracilis",
    "Tantilla hobartsmithi",
    "Tantilla melanocephala",
    "Tantilla nigriceps",
    "Tantilla planiceps",
    "Tantilla relicta",
    "Tantilla rubra",
    "Tantilla wilcoxi",
    "Tantilla yaquia",
    "Telescopus fallax",
    "Telescopus semiannulatus",
    "Thamnodynastes pallidus",
    "Thamnophis atratus",
    "Thamnophis brachystoma",
    "Thamnophis butleri",
    "Thamnophis chrysocephalus",
    "Thamnophis couchii",
    "Thamnophis cyrtopsis",
    "Thamnophis elegans",
    "Thamnophis eques",
    "Thamnophis gigas",
    "Thamnophis hammondii",
    "Thamnophis marcianus",
    "Thamnophis melanogaster",
    "Thamnophis ordinoides",
    "Thamnophis proximus",
    "Thamnophis pulchrilatus",
    "Thamnophis radix",
    "Thamnophis rufipunctatus",
    "Thamnophis saurita",
    "Thamnophis scalaris",
    "Thamnophis scaliger",
    "Thamnophis sirtalis",
    "Thamnophis validus",
    "Thamnosophis lateralis",
    "Thelotornis capensis",
    "Thelotornis usambaricus",
    "Trachyboa boulengeri",
    "Trimeresurus albolabris",
    "Trimeresurus erythrurus",
    "Trimeresurus gracilis",
    "Trimeresurus gramineus",
    "Trimeresurus hageni",
    "Trimeresurus insularis",
    "Trimeresurus macrops",
    "Trimeresurus malabaricus",
    "Trimeresurus nebularis",
    "Trimeresurus popeiorum",
    "Trimeresurus puniceus",
    "Trimeresurus purpureomaculatus",
    "Trimeresurus sabahi",
    "Trimeresurus stejnegeri",
    "Trimeresurus sumatranus",
    "Trimeresurus trigonocephalus",
    "Trimeresurus venustus",
    "Trimeresurus vogeli",
    "Trimorphodon biscutatus",
    "Trimorphodon lambda",
    "Trimorphodon lyrophanes",
    "Trimorphodon paucimaculatus",
    "Trimorphodon quadruplex",
    "Trimorphodon tau",
    "Trimorphodon vilkinsonii",
    "Tropidechis carinatus",
    "Tropidoclonion lineatum",
    "Tropidodipsas sartorii",
    "Tropidolaemus subannulatus",
    "Tropidolaemus wagleri",
    "Tropidonophis mairii",
    "Tropidophis melanurus",
    "Uromacer catesbyi",
    "Vermicella annulata",
    "Vipera ammodytes",
    "Vipera aspis",
    "Vipera berus",
    "Vipera latastei",
    "Vipera renardi",
    "Vipera seoanei",
    "Vipera transcaucasiana",
    "Vipera ursinii",
    "Vipera walser",
    "Virginia valeriae",
    "Xenochrophis flavipunctatus",
    "Xenochrophis maculatus",
    "Xenochrophis piscator",
    "Xenochrophis trianguligerus",
    "Xenochrophis vittatus",
    "Xenodermus javanicus",
    "Xenodon dorbignyi",
    "Xenodon merremii",
    "Xenodon rabdocephalus",
    "Xenopeltis unicolor",
    "Xenopholis scalaris",
    "Xerotyphlops vermicularis",
    "Zamenis lineatus",
    "Zamenis longissimus",
    "Zamenis scalaris",
    "Zamenis situla",
]


# -----------------------------------
# Metadata Mapping Function
# -----------------------------------
def get_snake_metadata(parsed):

    species_name = parsed["species_name"]

    row = df[df["binomial"].str.lower() == species_name.lower()]

    if row.empty:
        return {
            "Venomous status": "Unknown",
            "Recommended Antivenom": "Not Available"
        }

    row = row.iloc[0]

    venom_status = "Venomous" if row["venom_status"] == 1 else "Non-Venomous"
    antivenom = row["antivenom Name"] if row["antivenom Name"] != "Not applicable" else "None"
    habitat = row.get("region", "Not available")

    return {
        "species": species_name,
        "confidence": parsed["confidence"],
        "venom_status": venom_status,
        "antivenom": antivenom,
        "habitat": habitat,
        "about": parsed["about_snake"]
    }


# -----------------------------------
# LLM Snake Identifier
# -----------------------------------
def LLM_snake_identifier(description: str) -> dict:

    if client is None:
        return {"error": "LLM service unavailable"}

    system_prompt = (
        "You are a professional snake taxonomy expert.\n"
        "You MUST choose species_name strictly from the provided allowed list.\n"
        "Return ONLY valid JSON."
    )

    allowed_species_text = "\n".join(ALLOWED_SPECIES)

    user_prompt = f"""
Allowed species list:
{allowed_species_text}
Return JSON:
{{
  "species_name": "...",
  "confidence": "85%",
  "about_snake": "short description"
}}
Snake description:
\"\"\"{description}\"\"\"
"""

    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.1,
            stream=False
        )

        raw_output = response.choices[0].message.content.strip()

        # Extract JSON safely
        start = raw_output.find("{")
        end = raw_output.rfind("}") + 1

        if start == -1 or end == -1:
            raise ValueError("Invalid JSON output")

        parsed = json.loads(raw_output[start:end])

        # Validation
        if parsed["species_name"] not in ALLOWED_SPECIES:
            raise ValueError("Invalid species returned")

        return get_snake_metadata(parsed)

    except Exception as e:
        return {"error": str(e)}